name: Sync Fork

on:
  schedule:
    - cron: '25 * * * *' # Every saturday
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: gigich
          base: dev
          head: dev
